services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
    ports:
      - "9090:9090"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
<<<<<<< HEAD
      - /proc:/host/proc:ro,Z
      - /sys:/host/sys:ro,Z
      - /:/rootfs:ro,Z
=======
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro,Z
      - alertmanager-data:/alertmanager
    environment:
      - SMTP_SMARTHOST=${SMTP_SMARTHOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_AUTH_USERNAME=${SMTP_AUTH_USERNAME}
      - SMTP_AUTH_PASSWORD=${SMTP_AUTH_PASSWORD}
      - ALERT_EMAIL_TO=${ALERT_EMAIL_TO}
>>>>>>> 4befa75 (Big Update on RHEL configurations)
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host/rootfs'
    restart: unless-stopped

  grafana:
    image: grafana/grafana 
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana:Z
    restart: unless-stopped

volumes:
  grafana-data:
